[lpm]
db_backend = "sqlite"
packages_db = "./packages.sqlite"

[luas]
"Lua5.1" = "/usr/bin/lua5.1"
"Lua5.3" = "/usr/bin/lua5.3"

[sources.repositoryid]
trusted = true
cache = "$LPM_ROOT/repositories/repositoryid.toml"
url = "https://tabe.me/repositories/coal.toml"