[repository]
name = "Coal's Repository"
summary = "A repository for everything coal related"

[packages.hamming]
summary = "A package for finding the hamming distance between two strings"
package_type = "zip"
"1.0" = { source = "https://tabe.me/packages/hamming.1.0.zip" }

[packages.wolf]
summary = "A Lua library for creating static websites"
package_type = "git"
"1.0" = { source = "git://github.com/coalio/wolf.git" }