# Exactly the same toml as the samplerepository directory
# In this case, this one is the cache, while the other is the repository
# hosted online somewhere else.

[repository]
name = "Coal's Repository"
summary = "A repository for everything coal related"

[packages.hamming]
summary = "A package for finding the hamming distance between two strings"
package_type = "zip"
[packages.hamming.versions]
"1.0" = "https://tabe.me/packages/hamming.1.0.zip"

[packages.wolf]
summary = "A Lua library for creating static websites"
package_type = "git"
[packages.wolf.versions]
"1.0" = "git://github.com/coalio/wolf.git"