[package]
name = "hamming"
version = "1.0"
summary = "A package that provides a Hamming distance function"
license = "GPL-3.0"
repository = "https://github.com/coalio/me-at-the-zoo"
maintainer = "Coal <dibashtori@gmail.com>"

[source]
url = "https://raw.githubusercontent.com/coalio/me-at-the-zoo/master/hamming/version/1.0/1.0_hamming.zip"
package_type = "zip"

[run]
main = "hamming_demo.lua"
lua_version = ["LuaJIT2.0", "Lua5.3", "*"]

[support]
# lua_version is obligatory, but you can use "*" if you want
# however, that will throw a warning when installing as its possible that
# this package is not compatible with the most recent Lua version
lua_version = ["*"]
# plaform is obligatory, but you can use "*" if you want
# it wont throw a warning but its not recommended
platform = ["*"]