[package]
name = "hamming"
require="hamming.lua"
version = "1.0"
summary = "A package that provides a Hamming distance function"
license = "GPL-3.0"
homepage = "https://tabe.me/"
repository = "https://github.com/coalio/lpm"
maintainer = "Coal <coalio.gg@gmail.com>"
lua_version = "*"

[demo]
main="hamming_demo.lua"
lua_version=["LuaJIT2.0", "Lua5.3", "*"]

[support]
# lua_version is obligatory, but you can use "*" if you want
# however, that will throw a warning when installing as its possible that
# this package is not compatible with the most recent Lua version
lua_version = ["*"]
# platform is also obligatory, but you can also use "*" if you want
# in this case, it wont throw a warning but its not recommended
platform = ["*"]